#!/usr/bin/env python
#3/29/2012
#Converts a directory of video files into a summed duration

import os, sys, re, datetime
from video_duration import *

if len(sys.argv) > 1:
	path=sys.argv[1]  # insert the path to the directory of interest here
else:
	path = "./"

dirList=os.listdir(path)

for i in range(len(dirList)):
	dirList[i] = os.path.join(path, dirList[i])

#FIX: This summation will not work for videos of duration more than 24 hours. 3/29/12

accTime = []

#Make a list of datetime objects representing duration
for fname in dirList:
	ts = getDurationTimestamp(fname)
	accTime.append(datetime.timedelta(hours = ts.hour, seconds = ts.second, minutes = ts.minute))

#DIRTY DIRTY CODE. Please fix this, future self.
tVal = accTime[0]

for i in accTime[1:]:
	tVal += i

print tVal